iox-#590 Separate errors of posh and C binding
eclipse-iceoryx/iceoryx pull request #1028
Opened 2022-01-19 15:02 UTC by mossmaurice

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer
> Before looking at this PR, please have a look at #1027

* Move errors from hoofs to specific module (posh/ C binding) to make hoofs independent from posh and C binding

### Todo
* Swap arguments in `errorHandler()` call so that callable is last to avoid `nullptr` arg

### Discussion
* Switch to a builder pattern as next step?
* How to make the enum values unique?
  * Use an additional component identifier in the `errorHandler()` call? 
* Remove the `k` in front of the errors?

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #590

2022-01-19 16:00 UTC, mossmaurice commented on iceoryx_binding_c/include/iceoryx_binding_c/error_handling/error_handling.hpp
> +    kNO_ERROR = 2000,
This is one solution to the question "How to make the enum values unique all over iceoryx?" Another possibility would be to add an additional enum to the call with a component id.

2022-01-20 10:37 UTC, elfenpiff requested changes
Can we please keep this PR on hold until we figured out how the overall error concept in iceoryx looks like.
To call terminate is most likely not an option for ASIL D and we may have to make this either configurable or that some user can define custom callbacks to notify maybe some kind of watchdog or even throw an exception.

In those cases an error handler may is the more viable solution.

2022-01-24 16:42 UTC, elfenpiff requested changes
You checked the PR title check but the title does not follow our guidelines. Please add `iox-#???`.

2022-02-09 12:10 UTC, elfenpiff requested changes
Please perform the renaming of `error_handling.hpp` into `error_handler.hpp` in a separate PR.

2022-02-12 22:30 UTC, mossmaurice commented
This PR will be rebased onto #1100. Please refrain from reviewing it. I'll leave it open until there is a replacement to link to.

2022-02-28 09:03 UTC, mossmaurice commented
Superseded by #1170

2022-02-28 09:03 UTC, closed without merging