Iox #1049 create iceoryx docker shell script
eclipse-iceoryx/iceoryx pull request #1050
Opened 2022-01-26 16:56 UTC by elfenpiff

## Pre-Review Checklist for the PR Author

1. [ ] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [ ] Tests follow the [best practice for testing][testing]
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
    - [ ] Commit messages have the issue ID (`iox-#123 commit text`)
    - [ ] Commit messages are signed (`git commit -s`)
    - [ ] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [ ] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes **TBD**

2022-01-27 11:08 UTC, dkroenke requested changes
The script should be located either in the script or docker folder of tools.
Additionally it would be good to have a small hint to this in the advanced installation guide of the iceoryx documentation

2022-01-27 11:08 UTC, dkroenke commented on tools/ice_env.sh
> +               -dt --memory "4g" ${OS_VERSION}
It would be good to set the possible max. shared memory size with `--shm-size 2g` to a certain value. Default is 64 Mb which is not enough.

2022-01-28 08:40 UTC, dkroenke approved these changes

2022-01-28 09:33 UTC, FerdinandSpitzschnueffler commented on CHANGELOG.md
> +- Add `/tools/ice_env.sh` shell script to provide simple access to docker containers for CI debugging [#1049](https://github.com/eclipse-iceoryx/iceoryx/issues/1049)
```suggestion
- Add `/tools/scripts/ice_env.sh` shell script to provide simple access to docker containers for CI debugging [#1049](https://github.com/eclipse-iceoryx/iceoryx/issues/1049)
```

2022-01-28 09:46 UTC, FerdinandSpitzschnueffler submitted a review, later dismissed

2022-01-28 09:47 UTC, dkroenke approved these changes

2022-01-28 09:58 UTC, dkroenke requested changes
Please resolve merge conflicts

2022-01-28 10:01 UTC, FerdinandSpitzschnueffler approved these changes

2022-01-28 10:11 UTC, dkroenke approved these changes

2022-01-28 10:39 UTC, merged