Iox #27 create smart chunk
eclipse-iceoryx/iceoryx pull request #1081
Opened 2022-02-09 14:10 UTC by elfenpiff

## Pre-Review Checklist for the PR Author

1. [ ] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [ ] Tests follow the [best practice for testing][testing]
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
    - [ ] Commit messages have the issue ID (`iox-#123 commit text`)
    - [ ] Commit messages are signed (`git commit -s`)
    - [ ] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [ ] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes **TBD**

2022-02-09 14:37 UTC, elBoberido commented on iceoryx_posh/include/iceoryx_posh/popo/response.hpp
> +    using ForClientOnly = typename BaseType::template ForProducerOnly<S, TT>;
This must be `ForServerOnly`

2022-02-09 15:55 UTC, elfenpiff commented on iceoryx_posh/test/input/popo_toml_gateway_config.toml
> +	service = "這場考試_!*#:"
whoopsie

2022-02-09 15:55 UTC, elfenpiff commented on iceoryx_posh/test/input/popo_toml_gateway_config.toml
> +	service = "這場考試_!*#:"
This is my secret world domination plan ;)

2022-02-11 11:10 UTC, elBoberido commented on iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.hpp
> +    void publish() noexcept;
I think `deliver` is great since we use the same term further down in the building blocks

2022-02-11 17:08 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/internal/popo/request.inl
> +inline RequestHeader& Request<T>::getRequestHeader() noexcept
You are completely right but the Sample returns a user header reference. I could change it for request and response but than the APIs would diverge which I would very much dislike in this case.

But when I change it consistently the user header has to become also a pointer in the sample which would require some API changes throughout the code. As a compromise, would you be fine with accepting a reference here and I would fire out another PR based on this one where I change the reference to a pointer for the sample and those classes?

2022-02-11 17:13 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
>      virtual void publish(Sample<T, H>&& sample) noexcept = 0;
No, this is a requirement for all interfaces that they have to set the type alias `SampleType`.

2022-02-11 17:14 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/popo/request.hpp
> +class RequestInterface;
This should not pose a problem, for now I would leave it as it is. If it changes it is a simple search and replace.

2022-02-11 17:15 UTC, elfenpiff commented on iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
> +
I already did and just forgot to delete this file.

2022-02-11 17:18 UTC, elfenpiff commented on iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
> +        const_cast<uint32_t&>(sut.chunk.sample()->val) = dataValue;
This could be easy fixable. Should I rename it from `sample` to `data` in a separate PR?

2022-02-11 17:38 UTC, elBoberido commented on iceoryx_posh/include/iceoryx_posh/internal/popo/request.inl
> +inline RequestHeader& Request<T>::getRequestHeader() noexcept
Oh, you are right. It seems I overlooked the problem when I created the user header. I'm fine with your proposal

2022-02-11 17:42 UTC, elBoberido commented on iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.hpp
> +    R& getUserHeader() noexcept;
Right, my bad

2022-02-11 17:48 UTC, elBoberido commented on iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
> +        const_cast<uint32_t&>(sut.chunk.sample()->val) = dataValue;
If you like you can do. I'm not sure if it affects open PRs though.

2022-02-11 17:50 UTC, elBoberido commented on iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
> +        [&detectedError](const iox::Error error, const std::function<void()>&, const iox::ErrorLevel errorLevel) {
Was it intentional to use auto only for `ErrorLevel`?

2022-02-11 17:50 UTC, elBoberido approved these changes

2022-02-14 05:57 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/internal/popo/request.inl
> +inline RequestHeader& Request<T>::getRequestHeader() noexcept
Created issue #1101

2022-02-14 13:09 UTC, FerdinandSpitzschnueffler requested changes
Please add unique ids to the tests.

2022-02-14 13:09 UTC, FerdinandSpitzschnueffler commented on iceoryx_posh/include/iceoryx_posh/popo/request.hpp
> +/// These requests are send to the server via the iceoryx system.
```suggestion
/// These requests are sent to the server via the iceoryx system.
```

2022-02-14 13:40 UTC, elBoberido approved these changes

2022-02-14 13:46 UTC, FerdinandSpitzschnueffler approved these changes

2022-02-14 15:13 UTC, merged