Install includes to include/${PROJECT_NAME}
eclipse-iceoryx/iceoryx pull request #1189
Opened 2022-03-01 19:57 UTC by sloretz

Adds a CMake option `APPEND_PROJECT_NAME_TO_INCLUDEDIR` defaulting to `ON`
that appends ${PROJECT_NAME} to the directory headers are installed. This is to support ros2/ros2#1150.

Pretty similar to https://github.com/eclipse-cyclonedds/cyclonedds/pull/1169

When using ROS 2 and Colcon it's possible to have two versions of a package installed: typically one from the debian packages (like `ros-[rosdistro]-iceoryx-binding-c`) and another in a from-source workspace. In Colcon terms this is called "overriding a package", and the `/opt/ros/[rosdistro]` folder would be called the underlay while the from-source workspace would be called the overlay. A user would do this when they want to try a newer version of a package without building everything from source.

When two or more packages install their headers to the same directory in an underlay, it becomes possible for packages in the overlay to accidentally find the headers of an overridden package in the underlay. This can cause build failures or undefined behavior at runtime depending on the differences between the headers in the overridden and overriding packages. The exact conditions this happens are a little complicated, so I'll skip writing it out here. In ROS 2 we're solving the issue by making every package install its headers to a unique folder using `${PROJECT_NAME}`.

Signed-off-by: Shane Loretz <shane.loretz@gmail.com>

## Pre-Review Checklist for the PR Author

1. [ ] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [ ] Tests follow the [best practice for testing][testing]
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
    - [ ] Commit messages have the issue ID (`iox-#123 commit text`)
    - [ ] Commit messages are signed (`git commit -s`)
    - [ ] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [ ] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes **TBD**

2022-03-01 21:42 UTC, elBoberido commented
@dkroenke I guess this is also interesting for you

2022-03-02 00:17 UTC, sloretz commented on iceoryx_binding_c/CMakeLists.txt
> +endif()
>  Everything will be installed to ${PREFIX}/${PROJECT_NAME} not just the header

I didn't find this to be the case in my testing; only the paths the headers were installed are affected. [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) instead? How about I change the name of the variable to `INCLUDEDIR` or similar?

That said, there's a bug where `iceoryxversions.hpp` is still being installed to `include/`, so I'll fix that.

<details><summary>install tree before this PR</summary>


```
$ tree _sish_/containers/focal/_sandbox_/home/osrf/ws/ros2/install/iceoryx_*/
_sish_/containers/focal/_sandbox_/home/osrf/ws/ros2/install/iceoryx_binding_c/
├── include
│   └── iceoryx_binding_c
│       ├── api.h
│       ├── chunk.h
│       ├── client.h
│       ├── config.h
│       ├── enums.h
│       ├── iceoryx_binding_c_deployment.h
│       ├── internal
│       │   ├── c2cpp_binding.h
│       │   ├── c2cpp_enum_translation.hpp
│       │   ├── cpp2c_enum_translation.hpp
│       │   ├── cpp2c_publisher.hpp
│       │   ├── cpp2c_service_description_translation.hpp
│       │   ├── cpp2c_subscriber.hpp
│       │   └── cpp2c_waitset.hpp
│       ├── listener.h
│       ├── log.h
│       ├── node.h
│       ├── notification_info.h
│       ├── publisher.h
│       ├── request_header.h
│       ├── response_header.h
│       ├── runtime.h
│       ├── server.h
│       ├── service_description.h
│       ├── service_discovery.h
│       ├── subscriber.h
│       ├── types.h
│       ├── user_trigger.h
│       └── wait_set.h
├── lib
│   ├── cmake
│   │   └── iceoryx_binding_c
│   │       ├── iceoryx_binding_cConfig.cmake
│   │       ├── iceoryx_binding_cConfigVersion.cmake
│   │       ├── iceoryx_binding_cTargets.cmake
│   │       └── iceoryx_binding_cTargets-noconfig.cmake
│   └── libiceoryx_binding_c.so
└── share
    ├── colcon-core
    │   └── packages
    │       └── iceoryx_binding_c
    ├── doc
    │   └── iceoryx_binding_c
    │       └── LICENSE
    └── iceoryx_binding_c
        ├── hook
        │   ├── cmake_prefix_path.dsv
        │   ├── cmake_prefix_path.ps1
        │   ├── cmake_prefix_path.sh
        │   ├── ld_library_path_lib.dsv
        │   ├── ld_library_path_lib.ps1
        │   ├── ld_library_path_lib.sh
        │   ├── pkg_config_path.dsv
        │   ├── pkg_config_path_multiarch.dsv
        │   ├── pkg_config_path_multiarch.ps1
        │   ├── pkg_config_path_multiarch.sh
        │   ├── pkg_config_path.ps1
        │   └── pkg_config_path.sh
        ├── package.bash
        ├── package.dsv
        ├── package.ps1
        ├── package.sh
        └── package.zsh
_sish_/containers/focal/_sandbox_/home/osrf/ws/ros2/install/iceoryx_hoofs/
├── include
│   └── iceoryx_hoofs
│       ├── concurrent
│       │   ├── lockfree_queue.hpp
│       │   └── resizeable_lockfree_queue.hpp
│       ├── cxx
│       │   ├── algorithm.hpp
│       │   ├── attributes.hpp
│       │   ├── convert.hpp
│       │   ├── deadline_timer.hpp
│       │   ├── expected.hpp
│       │   ├── filesystem.hpp
│       │   ├── forward_list.hpp
│       │   ├── functional_interface.hpp
│       │   ├── function.hpp
│       │   ├── function_ref.hpp
│       │   ├── generic_raii.hpp
│       │   ├── helplets.hpp
│       │   ├── list.hpp
│       │   ├── method_callback.hpp
│       │   ├── newtype.hpp
│       │   ├── optional.hpp
│       │   ├── poor_mans_heap.hpp
│       │   ├── requires.hpp
│       │   ├── scoped_static.hpp
│       │   ├── serialization.hpp
│       │   ├── stack.hpp
│       │   ├── string.hpp
│       │   ├── types.hpp
│       │   ├── type_traits.hpp
│       │   ├── unique_ptr.hpp
│       │   ├── variant.hpp
│       │   ├── variant_queue.hpp
│       │   └── vector.hpp
│       ├── design_pattern
│       │   └── creation.hpp
│       ├── error_handling
│       │   └── error_handling.hpp
│       ├── internal
│       │   ├── concurrent
│       │   │   ├── active_object.hpp
│       │   │   ├── fifo.hpp
│       │   │   ├── fifo.inl
│       │   │   ├── lockfree_queue
│       │   │   │   ├── buffer.hpp
│       │   │   │   ├── buffer.inl
│       │   │   │   ├── cyclic_index.hpp
│       │   │   │   ├── cyclic_index.inl
│       │   │   │   ├── index_queue.hpp
│       │   │   │   ├── index_queue.inl
│       │   │   │   ├── lockfree_queue.inl
│       │   │   │   └── resizeable_lockfree_queue.inl
│       │   │   ├── loffli.hpp
│       │   │   ├── loffli.inl
│       │   │   ├── periodic_task.hpp
│       │   │   ├── periodic_task.inl
│       │   │   ├── smart_lock.hpp
│       │   │   ├── smart_lock.inl
│       │   │   ├── sofi.hpp
│       │   │   ├── sofi.inl
│       │   │   ├── taco.hpp
│       │   │   ├── trigger_queue.hpp
│       │   │   └── trigger_queue.inl
│       │   ├── cxx
│       │   │   ├── algorithm.inl
│       │   │   ├── convert.inl
│       │   │   ├── expected.inl
│       │   │   ├── forward_list.inl
│       │   │   ├── functional_interface.inl
│       │   │   ├── function_ref.inl
│       │   │   ├── helplets.inl
│       │   │   ├── list.inl
│       │   │   ├── method_callback.inl
│       │   │   ├── newtype
│       │   │   │   ├── assignment.hpp
│       │   │   │   ├── comparable.hpp
│       │   │   │   ├── constructor.hpp
│       │   │   │   ├── convertable.hpp
│       │   │   │   ├── internal.hpp
│       │   │   │   ├── protected_constructor.hpp
│       │   │   │   └── sortable.hpp
│       │   │   ├── newtype.inl
│       │   │   ├── optional.inl
│       │   │   ├── pair.hpp
│       │   │   ├── poor_mans_heap.inl
│       │   │   ├── reference_counter.hpp
│       │   │   ├── reference_counter.inl
│       │   │   ├── scoped_static.inl
│       │   │   ├── serialization.inl
│       │   │   ├── set.hpp
│       │   │   ├── stack.inl
│       │   │   ├── static_storage.hpp
│       │   │   ├── static_storage.inl
│       │   │   ├── storable_function.hpp
│       │   │   ├── storable_function.inl
│       │   │   ├── string.inl
│       │   │   ├── string_internal.hpp
│       │   │   ├── unique_id.hpp
│       │   │   ├── unique_ptr.inl
│       │   │   ├── variant.inl
│       │   │   ├── variant_internal.hpp
│       │   │   ├── variant_queue.inl
│       │   │   └── vector.inl
│       │   ├── design_pattern
│       │   │   ├── action.hpp
│       │   │   └── creation.inl
│       │   ├── file_reader
│       │   │   └── file_reader.hpp
│       │   ├── graphs
│       │   │   ├── directed_acyclic_graph.hpp
│       │   │   └── directed_graph.hpp
│       │   ├── objectpool
│       │   │   └── objectpool.hpp
│       │   ├── posix_wrapper
│       │   │   ├── access_control.hpp
│       │   │   ├── ipc_channel.hpp
│       │   │   ├── message_queue.hpp
│       │   │   ├── mutex.hpp
│       │   │   ├── posix_call.inl
│       │   │   ├── shared_memory_object
│       │   │   │   ├── allocator.hpp
│       │   │   │   ├── memory_map.hpp
│       │   │   │   └── shared_memory.hpp
│       │   │   ├── shared_memory_object.hpp
│       │   │   ├── system_configuration.hpp
│       │   │   └── unix_domain_socket.hpp
│       │   ├── relocatable_pointer
│       │   │   ├── atomic_relocatable_pointer.hpp
│       │   │   ├── atomic_relocatable_pointer.inl
│       │   │   ├── base_relative_pointer.hpp
│       │   │   ├── pointer_repository.hpp
│       │   │   ├── pointer_repository.inl
│       │   │   ├── relative_pointer_data.hpp
│       │   │   ├── relative_pointer_data.inl
│       │   │   ├── relative_pointer.hpp
│       │   │   ├── relative_pointer.inl
│       │   │   ├── relocatable_ptr.hpp
│       │   │   └── relocatable_ptr.inl
│       │   └── units
│       │       ├── duration.hpp
│       │       └── duration.inl
│       ├── log
│       │   ├── logcommon.hpp
│       │   ├── logger.hpp
│       │   ├── logging_free_function_building_block.hpp
│       │   ├── logging.hpp
│       │   ├── logmanager.hpp
│       │   └── logstream.hpp
│       ├── platform
│       │   ├── acl.hpp
│       │   ├── dlfcn.hpp
│       │   ├── errno.hpp
│       │   ├── fcntl.hpp
│       │   ├── file.hpp
│       │   ├── get [...]

2022-03-02 00:24 UTC, sloretz commented on iceoryx_binding_c/CMakeLists.txt
> +endif()
> which is also not a folder ending with ${PROJECT_NAME} but a folder named ${PROJECT_NAME}

Reworded description in 71944b2629c8f5762766ba7909835bef6ac46a23

> there's a bug where iceoryxversions.hpp is still being installed to include/

Fixed this bug in 5fab62c88ea692ce3f14210a617df754fc1baca6

2022-03-02 00:35 UTC, elBoberido commented on iceoryx_binding_c/CMakeLists.txt
> +endif()
oh, my bad

2022-03-02 08:59 UTC, elfenpiff requested changes
@sloretz 

Since we write safety critical code we have to ensure traceability at all times. This means no pull request without issue and every commit message requires the prefix `iox-#??? `.

I already created an issue from your pull request test, see: https://github.com/eclipse-iceoryx/iceoryx/issues/1194

Could you please adjust all the commit messages so that they have the prefix `iox-#1194 `.
You can do this with:
```
git rebase -i HEAD~3
```
write `edit` to all commit messages. Then with `git commit --amend` you can adjust the commit message and `git rebase --continue` goes then to the next message.

Finally you have to push this via `git push -f`.

2022-03-03 12:39 UTC, dkroenke approved these changes

2022-03-03 14:39 UTC, elBoberido approved these changes

2022-03-03 18:35 UTC, elfenpiff approved these changes

2022-03-03 18:42 UTC, dkroenke requested changes
There is some more evaluation needed here regarding the include paths

2022-03-03 18:44 UTC, elBoberido requested changes
After thinking a bit more about this, I'm still not sure why this is required. If the problem is that there are files which are not installed with a proper prefix, it should be sufficient to place `iceoryx_versions.hpp` into e.g. `iceoryx_hoofs` or to create a version header for each module

This is the current content of `prefix/include`
```
iceoryx_binding_c/
iceoryx_dds/
iceoryx_hoofs/
iceoryx_introspection/
iceoryx_posh/
iceoryx_versions.hpp
```

Would this also work for you

2022-03-03 21:55 UTC, sloretz commented
> After thinking a bit more about this, I'm still not sure why this is required. If the problem is that there are files which are not installed with a proper prefix, it should be sufficient to place iceoryx_versions.hpp into e.g. iceoryx_hoofs or to create a version header for each module

The problem doesn't come from a header not being in another folder inside the include directory.  Both before and after this PR users would use `#include <iceoryx_versions.hpp>` to include that header. The problem comes from multiple packages installing headers to the same include directory.

See how `PREFIX` is used here: 

https://github.com/eclipse-iceoryx/iceoryx/blob/f03e09fe6ee929a9831d9c7e74859fa6dbb3b007/iceoryx_hoofs/CMakeLists.txt#L95-L98

That `$<INSTALL_INTERFACE...` bit tells downstream targets to look for iceoryx's headers in `include/${PREFIX}`.

Say a user installs `ros-rolling-cyclonedds` which also installs `ros-rolling-iceoryx-binding-c` because CycloneDDS depends on iceoryx_binding_c. Those packages are installed to `/opt/ros/rolling` which is a merged workspace. Say the user wants to try a new version of iceoryx, and for simplicity lets say the new version is ABI compatible with the version in `ros-rolling-iceoryx-binding-c`, but adds a new method `iox_negative_zero_copy()`. The user has their own colcon workspace `~/ws` in which they add the newer version of iceoryx_binding_c to `~/ws/src/iceoryx_binding_c`. The user creates a CMake package `~/ws/src/coolstuff` which depends on CycloneDDS and iceoryx_binding_c, and creates an executable target `coolexe` that tries to use `iox_negative_zero_copy()`. It has this in its `CMakeLists.txt`.


```CMake
find_package(iceoryx_binding_c)
find_package(CycloneDDS)

# ...

target_link_libraries(coolexe CycloneDDS::ddsc iceoryx_binding_c::iceoryx_binding_c)
```


The build of `coolstuff` does not succeed.

The problem is the order passed to `target_link_libraries()`. The `CycloneDDS::ddsc` target says to add `/opt/ros/rolling/include` to the list of directories to search for headers. The `iceoryx_binding_c::iceoryx_binding_c` target says to add `~/ws/install/iceoryx_binding_c/include` to the list of directories to search for headers. When `coolexe` is compiled, the compiler sees that it is supposed to search for  `#include <iceoryx_binding_c/api.h>`, but it finds it in `/opt/ros/rolling/include/iceoryx_binding_c/api.h` first because the `CycloneDDS::ddsc` target told it to look for headers in `/opt/ros/rolling/include` first. The user can solve this by reordering the `target_link_libraries()` call/

```CMake
# In this example, this order would cause the build to succeed.
target_link_libraries(coolexe iceoryx_binding_c::iceoryx_binding_c CycloneDDS::ddsc)
```

However, that gets impractical with multiple packages depending on each other and the overridden package. The changes are subject to what packages are being overridden so they can't really be committed because coworkers may need a different order if they're overriding different packages. Lastly, it's hard to confirm the order is correct because depending on the differences between the headers of any overridden packages, the build may succeed but have undefined behavior at runtime.

Changing the location the headers are installed solves the problem. If the package `ros-rolling-iceoryx` installs it's headers to `/opt/ros/rolling/include/iceoryx_binding_c` (such that the full path to `api.h` is `/opt/ros/rolling/include/iceoryx_binding_c/iceoryx_binding_c/api.h`), then the compiler won't find the underlay version of `iceoryx_binding_c/api.h` when it searches the include directory given by the `CycloneDDS::ddsc` target.

2022-03-03 23:50 UTC, sloretz commented
> would it also work for you if we add iceoryx/vX.Y.Z instead of ${PROJECT_NAME} so that we have include/iceoryx/v2.0.0/iceoryx_binding_c/api.h?

Definitely! 76c4304f7 does exactly that.

> Could you please update doc/website/release-notes/iceoryx-v2-0-0.md and add the issue which will be closed to the feature section

Updated changelog in b09566d98

<details><summary>Here's the new install tree with this PR</summary>

```
_sish_/containers/focal/_sandbox_/home/osrf/ws/ros2/install/iceoryx_binding_c/
├── include
│   └── iceoryx
│       └── v1.90.0
│           └── iceoryx_binding_c
│               ├── api.h
│               ├── chunk.h
│               ├── client.h
│               ├── config.h
│               ├── enums.h
│               ├── iceoryx_binding_c_deployment.h
│               ├── internal
│               │   ├── c2cpp_binding.h
│               │   ├── c2cpp_enum_translation.hpp
│               │   ├── cpp2c_enum_translation.hpp
│               │   ├── cpp2c_publisher.hpp
│               │   ├── cpp2c_service_description_translation.hpp
│               │   ├── cpp2c_subscriber.hpp
│               │   └── cpp2c_waitset.hpp
│               ├── listener.h
│               ├── log.h
│               ├── node.h
│               ├── notification_info.h
│               ├── publisher.h
│               ├── request_header.h
│               ├── response_header.h
│               ├── runtime.h
│               ├── server.h
│               ├── service_description.h
│               ├── service_discovery.h
│               ├── subscriber.h
│               ├── types.h
│               ├── user_trigger.h
│               └── wait_set.h
├── lib
│   ├── cmake
│   │   └── iceoryx_binding_c
│   │       ├── iceoryx_binding_cConfig.cmake
│   │       ├── iceoryx_binding_cConfigVersion.cmake
│   │       ├── iceoryx_binding_cTargets.cmake
│   │       └── iceoryx_binding_cTargets-noconfig.cmake
│   └── libiceoryx_binding_c.so
└── share
    ├── colcon-core
    │   └── packages
    │       └── iceoryx_binding_c
    ├── doc
    │   └── iceoryx_binding_c
    │       └── LICENSE
    └── iceoryx_binding_c
        ├── hook
        │   ├── cmake_prefix_path.dsv
        │   ├── cmake_prefix_path.ps1
        │   ├── cmake_prefix_path.sh
        │   ├── ld_library_path_lib.dsv
        │   ├── ld_library_path_lib.ps1
        │   ├── ld_library_path_lib.sh
        │   ├── pkg_config_path.dsv
        │   ├── pkg_config_path_multiarch.dsv
        │   ├── pkg_config_path_multiarch.ps1
        │   ├── pkg_config_path_multiarch.sh
        │   ├── pkg_config_path.ps1
        │   └── pkg_config_path.sh
        ├── package.bash
        ├── package.dsv
        ├── package.ps1
        ├── package.sh
        └── package.zsh
_sish_/containers/focal/_sandbox_/home/osrf/ws/ros2/install/iceoryx_hoofs/
├── include
│   └── iceoryx
│       └── v1.90.0
│           └── iceoryx_hoofs
│               ├── concurrent
│               │   ├── lockfree_queue.hpp
│               │   └── resizeable_lockfree_queue.hpp
│               ├── cxx
│               │   ├── algorithm.hpp
│               │   ├── attributes.hpp
│               │   ├── convert.hpp
│               │   ├── deadline_timer.hpp
│               │   ├── expected.hpp
│               │   ├── filesystem.hpp
│               │   ├── forward_list.hpp
│               │   ├── functional_interface.hpp
│               │   ├── function.hpp
│               │   ├── function_ref.hpp
│               │   ├── generic_raii.hpp
│               │   ├── helplets.hpp
│               │   ├── list.hpp
│               │   ├── method_callback.hpp
│               │   ├── newtype.hpp
│               │   ├── optional.hpp
│               │   ├── poor_mans_heap.hpp
│               │   ├── requires.hpp
│               │   ├── scoped_static.hpp
│               │   ├── serialization.hpp
│               │   ├── stack.hpp
│               │   ├── string.hpp
│               │   ├── types.hpp
│               │   ├── type_traits.hpp
│               │   ├── unique_ptr.hpp
│               │   ├── variant.hpp
│               │   ├── variant_queue.hpp
│               │   └── vector.hpp
│               ├── design_pattern
│               │   └── creation.hpp
│               ├── error_handling
│               │   └── error_handling.hpp
│               ├── internal
│               │   ├── concurrent
│               │   │   ├── active_object.hpp
│               │   │   ├── fifo.hpp
│               │   │   ├── fifo.inl
│               │   │   ├── lockfree_queue
│               │   │   │   ├── buffer.hpp
│               │   │   │   ├── buffer.inl
│               │   │   │   ├── cyclic_index.hpp
│               │   │   │   ├── cyclic_index.inl
│               │   │   │   ├── index_queue.hpp
│               │   │   │   ├── index_queue.inl
│               │   │   │   ├── lockfree_queue.inl
│               │   │   │   └── resizeable_lockfree_queue.inl
│               │   │   ├── loffli.hpp
│               │   │   ├── loffli.inl
│               │   │   ├── periodic_task.hpp
│               │   │   ├── periodic_task.inl
│               │   │   ├── smart_lock.hpp
│               │   │   ├── smart_lock.inl
│               │   │   ├── sofi.hpp
│               │   │   ├── sofi.inl
│               │   │   ├── taco.hpp
│               │   │   ├── trigger_queue.hpp
│               │   │   └── trigger_queue.inl
│               │   ├── cxx
│               │   │   ├── algorithm.inl
│               │   │   ├── convert.inl
│               │   │   ├── expected.inl
│               │   │   ├── forward_list.inl
│               │   │   ├── functional_interface.inl
│               │   │   ├── function_ref.inl
│               │   │   ├── helplets.inl
│               │   │   ├── list.inl
│               │   │   ├── method_callback.inl
│               │   │   ├── newtype
│               │   │   │   ├── assignment.hpp
│               │   │   │   ├── comparable.hpp
│               │   │   │   ├── constructor.hpp
│               │   │   │   ├── convertable.hpp
│               │   │   │   ├── internal.hpp
│               │   │   │   ├── protected_constructor.hpp
│               │   │   │   └── sortable.hpp
│               │   │   ├── newtype.inl
│               │   │   ├── optional.inl
│               │   │   ├── pair.hpp
│               │   │   ├── poor_mans_heap.inl
│               │   │   ├── reference_counter.hpp
│               │   │   ├── reference_counter.inl
│               │   │   ├── scoped_static.inl
│               │   │   ├── serialization.inl
│               │   │   ├── set.hpp
│               │   │   ├── stack.inl
│               │   │   ├── static_storage.hpp
│               │   │   ├── static_storage.inl
│               │   │   ├── storable_function.hpp
│               │   │   ├── storable_function.inl
│               │   │   ├── string.inl
│               │   │   ├── string_internal.hpp
│               │   │   ├── unique_id.hpp
│               │   │   ├── unique_ptr.inl
│               │   │   ├── variant.inl
│               │   │   ├── variant_internal.hpp
│               │   │   ├── variant_queue.inl
│               │   │   └── vector.inl
│               │   ├── design_pattern
│               │   │   ├── action.hpp
│               │   │   └── creation.inl
│               │   ├── file_reader
│               │   │   └── file_reader.hpp
│               │   ├── graphs
│               │   │   ├── directed_acyclic_graph.hpp
│               │   │   └── directed_graph.hpp
│               │   ├── objectpool
│               │   │   └── objectpool.hpp
│               │   ├── posix_wrapper
│               │   │   ├── access_control.hpp
│               │   │   ├── ipc_channel.hpp
│               │   │   ├── message_queue.hpp
│               │   │   ├── mutex.hpp
│               │   │   ├── posix_call.inl
│               │   │   ├── shared_memory_object
│               │   │   │   ├── allocator.hpp
│               │   │   │   ├── memory_map.hpp
│               │   │   │   └── shared_memory.hpp
│               │   │   ├── shared [...]

2022-03-03 23:58 UTC, elBoberido approved these changes
@sloretz thanks for your patience

@dkroenke do you also like the new approach?

2022-03-04 09:58 UTC, dkroenke approved these changes
I'm good with the changes here, since it covers not all CMake projects in iceoryx an additional PR is made here: https://github.com/eclipse-iceoryx/iceoryx/pull/1232

2022-03-04 10:10 UTC, merged