iox-#1196 Suppress clang-tidy and AUTOSAR warnings in `PointerRepository`
eclipse-iceoryx/iceoryx pull request #1534
Opened 2022-07-20 09:27 UTC by mossmaurice

Signed-off-by: Simon Hoinkis <simon.hoinkis@apex.ai>

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

* Suppress clang-tidy and AUTOSAR warning in `PointerRepository`

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #1196 (partly)

2022-07-20 09:29 UTC, mossmaurice commented
@elfenpiff @FerdinandSpitzschnueffler The magic number in `pointer_repository.hpp` is moved to a `constexpr` variables as part of #1521

2022-07-20 15:12 UTC, elfenpiff requested changes
It took my now 2 full days to fix all the overlooked warnings in cxx. So I made up a new rule, could you please add all files which you fixed to `/clang-tidy-files-to-scan.txt`

When the CI approves that everything is fixed I will approve as well.
Sorry for add this little burden on you but we have to be more efficient.

2022-07-20 20:31 UTC, mossmaurice commented on iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
> +        // AXIVION Next Construct AutosarC++19_03-A5.2.4 : Cast is needed for pointer arithmetic
@FerdinandSpitzschnueffler I don't get any running clang-tidy 13. Can you check?

2022-07-21 13:20 UTC, elfenpiff commented on iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
> +        // AXIVION Next Construct AutosarC++19_03-A5.2.4 : Cast is needed for pointer arithmetic
@mossmaurice When it is added to the diff scan file it will be scanned extensively and there is no need for a manual one.

2022-07-21 13:20 UTC, elfenpiff submitted a review, later dismissed

2022-07-21 14:17 UTC, FerdinandSpitzschnueffler commented on iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
> +        // AXIVION Next Construct AutosarC++19_03-A5.2.4 : Cast is needed for pointer arithmetic
My concern was more about the justification, not that there is an additional warning. I would prefer if we state why the `reinterpret_cast`s are safe.

2022-07-25 10:15 UTC, mossmaurice commented on .clang-tidy-diff-scans.txt
> +./iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
@FerdinandSpitzschnueffler Correct

2022-07-25 10:55 UTC, FerdinandSpitzschnueffler approved these changes

2022-07-25 11:48 UTC, elfenpiff approved these changes

2022-07-25 11:55 UTC, merged