iox-#1609 Add log message before terminating
eclipse-iceoryx/iceoryx pull request #1610
Opened 2022-09-06 18:35 UTC by elBoberido

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. ]x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

Add a log message to give the user a clue what happened.

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #1609

2022-09-07 08:13 UTC, dkroenke requested changes

2022-09-07 08:13 UTC, dkroenke commented on doc/website/release-notes/iceoryx-unreleased.md
> +- ocking_policy.hpp calls error handler without log message [\#1609](https://github.com/eclipse-iceoryx/iceoryx/issues/1609)
```suggestion
- locking_policy.hpp calls error handler without log message [\#1609](https://github.com/eclipse-iceoryx/iceoryx/issues/1609)
```

2022-09-07 08:13 UTC, dkroenke commented on iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
> +                      "terminated or the resources were cleaned up by RouDi due to an unresponsive application.";
```suggestion
        LogFatal() << "Locking of an inter-process mutex failed! This indicates that the application holding the lock "
                      "was terminated or the resources were cleaned up by RouDi due to an unresponsive application.";
```

2022-09-07 08:37 UTC, elfenpiff reviewed
Looks good. Fix the spelling mistakes and I will approve it.

2022-09-07 11:27 UTC, dkroenke approved these changes

2022-09-08 11:20 UTC, elfenpiff approved these changes

2022-09-08 11:24 UTC, merged