Iox #714 call reset in subscriber destructor
eclipse-iceoryx/iceoryx pull request #730
Opened 2021-04-14 23:26 UTC by FerdinandSpitzschnueffler

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer
This PR fixes the runtime error described in #714 by calling `m_trigger.reset()` in the destructors of `SubscriberImpl` and `UntypedSubscriberImpl`.

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #714

2021-04-14 23:45 UTC, elfenpiff requested changes

2021-04-14 23:45 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
> +SubscriberImpl<T, H, BaseSubscriber_t>::~SubscriberImpl()
inline missing

2021-04-14 23:45 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl
> +UntypedSubscriberImpl<BaseSubscriber_t>::~UntypedSubscriberImpl()
inline missing

2021-04-14 23:45 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
> +    virtual ~SubscriberImpl();
Please add noexcept

2021-04-14 23:45 UTC, elfenpiff commented on iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp
> +    virtual ~UntypedSubscriberImpl();
Please add noexcept

2021-04-14 23:45 UTC, elfenpiff commented on iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp
> +    m_subscriber.reset();
maybe we should comment in both tests that we are testing the undefined behavior sanitizer which will go off when the subscriber goes out of scope and the trigger tries to access the child object after the child dtor is finished and it does no longer exist

2021-04-15 01:09 UTC, elfenpiff submitted a review, later dismissed

2021-04-15 01:49 UTC, elBoberido submitted a review, later dismissed

2021-04-15 07:36 UTC, MatthiasKillat commented on iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp
> +/// scope, the trigger tries to access it but SubscriberImpl does not longer exist. This is catched by the
caught

2021-04-15 07:39 UTC, MatthiasKillat commented on iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp
> +TEST_F(PubSubListener_IntegrationTest, SubscriberGoesOutOfScopeAndDeatchingWorks)
Detaching

2021-04-15 07:50 UTC, MatthiasKillat submitted a review, later dismissed

2021-04-15 08:26 UTC, mossmaurice approved these changes

2021-04-15 08:53 UTC, elBoberido approved these changes

2021-04-15 09:02 UTC, merged