Iox #842 cleanup memory provider and memory block
eclipse-iceoryx/iceoryx pull request #843
Opened 2021-06-09 15:03 UTC by elBoberido

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer

This fixes some of the requests from #840 

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #842

2021-06-11 09:21 UTC, mossmaurice requested changes
Please double check all the copyright headers, otherwise LGTM.

In general, should there be death tests added for methods that use `not_null`?

2021-06-11 09:21 UTC, mossmaurice commented on iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_collection_memory_block.hpp
> +    /// @copydoc MemoryBlock::size
Please adapt the copyright header

2021-06-11 09:21 UTC, mossmaurice commented on iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_segment_manager_memory_block.hpp
> +    /// @copydoc MemoryBlock::size
Please adapt the copyright header

2021-06-11 09:21 UTC, mossmaurice commented on iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/port_pool_memory_block.hpp
> +    /// @copydoc MemoryBlock::size
Copyright header update needed here too ;)

2021-06-11 09:21 UTC, mossmaurice commented on iceoryx_posh/include/iceoryx_posh/roudi/memory/generic_memory_block.hpp
>      GenericMemoryBlock& operator=(const GenericMemoryBlock&) = delete;
Same here

2021-06-11 09:21 UTC, mossmaurice commented on iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_block.hpp
> +    virtual ~MemoryBlock() = default;
`noexcept`?

2021-06-11 11:17 UTC, elBoberido commented
Regarding the death test for `not_null`. In this specific case it's not really possible since it's a protected method and on the caller side this is only called if it's not a `nullptr`. I would have used a reference, but that's not possible with a `void`.

In general I also wouldn't do death tests for parameter with `not_null` since we also don't do death tests for methods with references as parameter and you could easily have something like this
```cpp
int foo (int& i) {
    return i;
}
int bar(int* i) {
    return foo(*i);
}
int main() {
    return bar(nullptr); // crash will happen on `return i;` not `return foo(*i);`
}
```
As long as we already tested that `not_null` itself terminates, it is not necessary to test it again everywhere else it is used.

2021-06-11 12:19 UTC, dkroenke commented on iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_block.hpp
> +    virtual void memoryAvailable(cxx::not_null<void*> memory) noexcept;
I understand the purpose of this "callback" but find the name a bit misleading.
It is called automatically at a certain condition so we could set the prefix "on" here.
Maybe something like "onMemoryBlockCreated". But these are only my 2 cents.

2021-06-12 14:12 UTC, mossmaurice submitted a review, later dismissed

2021-06-14 07:34 UTC, dkroenke commented on iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_segment_manager_memory_block.hpp
> +    /// @copydoc MemoryBlock::memoryAvailable
should be: onMemoryAvailable

2021-06-14 09:22 UTC, mossmaurice approved these changes

2021-06-14 09:22 UTC, dkroenke approved these changes

2021-06-14 09:55 UTC, merged